name: Render HTML to PNG

on:
  push:
    paths:
      - 'index.html'
      - '.github/workflows/render-html.yml'

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install wkhtmltoimage
        run: sudo apt-get install -y wkhtmltopdf

      - name: Render HTML to PNG
        run: |
          mkdir -p files
          wkhtmltoimage --width 320 --height 1200 --quality 100 index.html files/output.png

      - name: Commit rendered PNG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add files/output.png
          git commit -m "Render index.html to output.png [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
