name: Render HTML to PNG

on:
  push:
    paths:
      - 'index.html'
      - '.github/workflows/render-html.yml'

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install wkhtmltoimage and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf imagemagick

      - name: Render HTML to high-res PNG
        run: |
          mkdir -p files
          wkhtmltoimage --width 1920 --height 1080 --quality 100 index.html files/temp_output.png

      - name: Resize PNG to 320x180
        run: |
          convert files/temp_output.png -resize 320x180 files/output.png
          rm files/temp_output.png

      - name: Commit rendered PNG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add files/output.png
          git commit -m "Render index.html to output.png [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
