name: Generate Screenshot

on:
  schedule:
    - cron: '*/15 5-17 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Buat folder files jika belum ada
      run: mkdir -p files

    - name: Download screenshot
      run: |
        curl "https://image.thum.io/get/width/4800/https://krayondk.github.io/log/" --output files/result.png

    - name: Force commit and push result.png ke folder files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add files/result.png
        git commit -m "Auto-update result.png screenshot" || echo "Nothing to commit"
        git push origin HEAD --force
